import random
#This program genrates code langvage that cant be understanded by everyone! 
#this program will encode and decode that text which is entered

#welcome text
Welcome="* Welcome to code langvage genrator made by akash *\n"
print(Welcome.upper().center(110))

#Encoder or Decoder are Choosen here
while True: # error handling
    try:
        print("Do you want encoder [TYPE 0 FOR THAT] or decoder [TYPE 1 FOR THAT]..?\n",sep=None,end=None)
        choice=int(input())

        if choice==0 or 1:
            break
    except:
        print("\nError occured..! please try again! \n",sep=None,end=None)

    
    #user text input are taken here
try:
    user_text=input("\nPlease enter the text that you want to convert :\n")
    print("\nYour text is in safe hand : ) , don't worry...!\n\nHere's your converted code!\n",sep=None,end=None)

except:
    print("\nError occured..! please try again! \n",sep=None,end=None)
    
    exit()

#encoding is done here
if choice==0:
    user_text=user_text.split()  #changing sentance to list
    try:
        for word in (user_text):
            lenword=len(word)
            if lenword<3 and lenword>0 : # for less than 3 letters
                rev="" # block to reverse a list's every element
                for letter in word:
                    
                    rev=letter+rev
                print(rev,end=' ')
            
            else:
                word3=word[0]
                word1=word[1:]
                word1=word1+word3
                
                #random varibale list
                r_l=['g','e','y','a','h','c','k','t','j'] # block of code to put 3-3 random letter infront and back
                ran= random.sample(r_l,3)
                for i in ran:
                    word1=i+word1
                ran= random.sample(r_l,3)
                for i in ran:
                    word1=word1+i
                print(word1,end=' ')
    except:
        print("\n got an error try again\n")

#Decoding is done here
elif choice==1:
    try:    
        user_text=user_text.split()
        for word in user_text:
            length=len(word)
            
            if 4 <= length <= 8:
                raise ValueError("We do not support other language input for decoding! Please enter language that is generated by us only.")
            if length<3 and length>0: # for less than 3 letters
            
                rev="" # block to reverse a list's every element
                for letter in word:
                        
                    rev=letter+rev
                print(rev,end=' ')

            else:
                word=word[3:-3]
                #random variables are now removed
                repword=word[-1]
                word=word[:-1]
                word=repword+word
                print(word,sep=None,end=" ")
    except:
        print("\nerror occured! please try again!")
        
        



    
